// import "./object/chapter1"
// import "./object/chapter2"
// import "./object/chapter3"
// import "./function/chapter0"
// import "./function/chapter1"
// import "./function/chapter2"
// import "./function/chapter3"
// import "./function/chapter4"
// import "./bom/chapter1"
// import "./bom/chapter2-location"
import "./bom/chapter3-navigator"
// import "./storage/cookie"